### ISSUE TITLE
Angular material

### ISSUE THREAD

**Issue by AnuragBhatt** [angular-community/angular-community#6]
My angular material dialog is popping up on the bottom of the screen, rather than in the middle. 
It also does not close on click, but rather whenever I hit escape.
The page is stuck until a minute or so, and then it is available for clicking.
If I try bringing up again, it will keep on stacking down under.

Please provide me any pointer how to resolve it.

**Comment by mvdluit** [comment]
@AnuragBhatt we do not provide support here, please ask your question on https://discord.gg/angular and provide a stackblitz reproduction of your issue.
